### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by ahmadalfy** [kodemoapp/feedback#4]
Syntax highlighting for TypeScript files would be a great addition. This is extremely unimportant request at this stage of the project.

**Comment by hakimel** [comment]
We should definitely support Typescript. Doesn't look like it's included in CodeMirror 6 but I've been considering a switch to Monaco to add support for more languages.

For the short term I'll add JavaScript highlighting for .ts files.

**Comment by hakimel** [comment]
I've added support for TypeScript. Turns out it did exist as an option in CodeMirror 6's JS language pack.

Also added Ruby, Swift, shell and YAML.
